source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.3'
gem 'minimal-mistakes-jekyll'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-include-cache'
gem 'jekyll-remote-theme'
gem 'jekyll-seo-tag'
gem 'jekyll-archives'
