name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: bundle install

      - name: Build the site with Jekyll
        run: bundle exec jekyll build

      # Optional: 빌드 결과를 artifact로 업로드 (필요시)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

      # Optional: GitHub Pages에 자동 배포 (Peaceiris/actions-gh-pages 사용)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
